// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjmyjywpzdicrjnjbzml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbXlqeXdwemRpY3Jqbmpiem1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDk2NTMsImV4cCI6MjA2Mzg4NTY1M30.Vl9t1DBb1wp64-waWv29v_eFzGv4zqxjuB6wsuULAVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);